version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    networks:
      default:
        ipv4_address: 10.65.80.74
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
  # web:
  #   build: 
  #     context: .
  #     dockerfile: ./docker/django/Dockerfile
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   networks:
  #     default:
  #       ipv4_address: 10.65.80.73
  #     nginx_network:
  #   restart: always
  django-app:
    build:
      context: .
      dockerfile: ./docker/uwsgi/Dockerfile
    command: uwsgi --ini docker/uwsgi/uwsgi.ini
    volumes:
      - .:/code
      - django-socket:/home/socket
    networks:
      default:
        ipv4_address: 10.65.80.75
    restart: always
    depends_on: 
      - db

  django-web:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/uwsgi_params:/home/uwsgi_params
      - django-socket:/home/socket
      - .:/code
    networks:
      default:
        ipv4_address: 10.65.80.76
      nginx_network:
    depends_on: 
      - django-app

networks:
  default:
    ipam:
      config:
      - subnet: 10.65.80.0/24
  nginx_network:
    external: true

volumes:
  django-socket: