version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    networks:
      default:
        ipv4_address: 10.65.80.74
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
  web:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      default:
        ipv4_address: 10.65.80.73
      nginx_network:
    restart: always

networks:
  default:
    ipam:
      config:
      - subnet: 10.65.80.0/24
  nginx_network:
    external: true